
obj-$(CONFIG_VIDEO_ROCKCHIP_VPU_44) += rockchip-vpu-44.o

rockchip-vpu-44-y += rockchip_vpu.o \
		rockchip_vpu_dec.o \
		rockchip_vpu_enc.o \
		rockchip_vpu_hw.o \
		rk3288_vpu_hw.o \
		rk3288_vpu_hw_h264d.o \
		rk3288_vpu_hw_h264e.o \
		rk3288_vpu_hw_vp8d.o \
		rk3288_vpu_hw_vp8e.o \
		rk3399_vpu_hw.o \
		rk3399_vpu_hw_vp8d.o \
		rk3399_vpu_hw_h264e.o \
		rk3399_vpu_hw_jpege.o \
		rk3399_vpu_hw_vp8e.o \
		rk3399_vdec_hw.o \
		rk3399_vdec_hw_h264d.o \
		rk3399_vdec_hw_vp9d.o \
