#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "usage: $1 root@192.168.88.231:"
  echo "usage: $1 /media/ayufan/ROOT-A/"
  exit 1
fi

set -xe

find out/linux_modules/lib/modules/4.4.167-rockchip-dev/ -name *.ko | xargs aarch64-linux-gnu-strip --strip-debug

[[ "$1" == *:* ]] || [[ -e $1/lib/modules/4.4.167-rockchip-dev/ ]]

if [[ "$1" == *:* ]]; then
  scp arch/arm64/boot/Image $1/boot/vmlinuz-4.4.167-rockchip-dev
  scp arch/arm64/boot/dts/rockchip/rk3399-rockpro64*.dtb $1/boot/dts/
  #scp -r out/linux_modules/lib/modules/4.4.167-rockchip-dev/kernel $1/lib/modules/4.4.167-rockchip-dev/
elif [[ -e $1/lib/modules/4.4.167-rockchip-dev/ ]]; then
  rsync --progress -u -a arch/arm64/boot/Image $1/boot/vmlinuz-4.4.167-rockchip-dev
  rsync --progress -u -a arch/arm64/boot/dts/rockchip/rk3399-rockpro64*.dtb $1/boot/dts/
  rsync --progress -u -a --delete out/linux_modules/lib/modules/4.4.167-rockchip-dev/ $1/lib/modules/4.4.167-rockchip-dev/
  sync
else
  echo "Unknown format."
  exit 1
fi
